import { Forum } from "next/font/google";
import "./globals.css";
import 'tailwindcss/tailwind.css';
import 'flowbite';

const Forum_init = Forum({ subsets: ["latin"],weight:["400"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     
      <body className={Forum_init.className}>
        {children}
      </body>
    </html>
  );
}
